- name: copy repo file
  ansible.builtin.template:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - fontconfig
    - java-17-openjdk
    - jenkins

- name: start jenkins service
  ansible.builtin.systemd_service:
    name: jenkins
    state: started
    enabled: yes


