- name: disable nodejs <18
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enable nodejs
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install nginx
  ansible.builtin.dnf:
    name: nodejs
    state: latest

- name: Create a user
  ansible.builtin.user:
    name: roboshop

- name: Remove directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Make a directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download frontend code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/cart.zip
    dest: /tmp/cart.zip

- name: Unarchive frontend
  ansible.builtin.unarchive:
    src: /tmp/cart.zip
    dest: /app
    remote_src: yes

- name: Install npm package
  community.general.npm:
    name: npm
    path: /app

- name: Copy file
  ansible.builtin.template:
    src: Catalogue.service
    dest: /etc/systemd/system/cart.service

- name: Start and enable nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes






